<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32" started-at="2020-08-17T08:46:11Z" finished-at="2020-08-17T08:46:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32" started-at="2020-08-17T08:46:11Z" finished-at="2020-08-17T08:46:11Z">
      <class name="base.IianxiTestNG">
        <test-method status="PASS" signature="beforet()[pri:0, instance:base.IianxiTestNG@2cb4c3ab]" name="beforet" is-config="true" duration-ms="10" started-at="2020-08-17T16:46:11Z" finished-at="2020-08-17T16:46:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforet -->
        <test-method status="SKIP" signature="test1(java.lang.String, java.lang.String)[pri:0, instance:base.IianxiTestNG@2cb4c3ab]" name="test1" duration-ms="0" started-at="2020-08-17T16:46:11Z" data-provider="user1" finished-at="2020-08-17T16:46:11Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void base.IianxiTestNG.test1(java.lang.String,java.lang.String) requires a @DataProvider named : user1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void base.IianxiTestNG.test1(java.lang.String,java.lang.String) requires a @DataProvider named : user1
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="overtest()[pri:0, instance:base.IianxiTestNG@2cb4c3ab]" name="overtest" is-config="true" duration-ms="1" started-at="2020-08-17T16:46:11Z" finished-at="2020-08-17T16:46:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- overtest -->
      </class> <!-- base.IianxiTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
